@hostname = http://mydomain.com:5000

# @name register_account
POST {{hostname}}/api/auth/register-account HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password",
    "firstName": "Bob",
    "lastName": "L"
}

###

# @name register_user
POST {{hostname}}/api/auth/register-user HTTP/1.1
Content-Type: application/json

{
    "role": "mentee"
}

###

# @name login
@email = {{register_account.request.body.email}}
@password = {{register_account.request.body.password}}
@role = {{register_user.request.body.role}}
POST {{hostname}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "{{email}}",
    "password" : "{{password}}",
    "role": "{{role}}"
}

###

# @name view_users
GET {{hostname}}/api/auth/users

###

# @name create_relation
# You must be logged in as a mentee for this to work
# SELECT * FROM "user" WHERE ("role"='mentor');
POST {{hostname}}/api/relations/create-relation
Content-Type: application/json

{
    "mentorID": 1
}

###

# @name get_relation
GET {{hostname}}/api/relations/get-relations
