@hostname = http://localhost:5000

# @name register
POST {{hostname}}/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "{{$randomInt 0 10000}}@gmail.com",
    "password": "password",
    "firstName": "Bob",
    "lastName": "L",
    "role": "admin"
}

###

# @name login
@email = {{register.request.body.email}}
POST {{hostname}}/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "{{email}}",
    "password": "password"
}

###

# @name viewUsers

@token = {{login.response.headers.Authorization}}
GET {{hostname}}/api/auth/users
Authorization: Bearer {{token}}
